fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

principal:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"



