<?php

namespace App\AdminBundle\Repository;

/**
 * CantidadUtilizadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CantidadUtilizadaRepository extends \Doctrine\ORM\EntityRepository
{
}
