<?php

namespace App\AdminBundle\Repository;

/**
 * ComentarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentarioRepository extends \Doctrine\ORM\EntityRepository
{
	public function getNumeroComentario()
	{
		$qp = $this->createQueryBuilder('c')->select('count(c.id)');
		
		return $qp->getQuery()->getSingleScalarResult();
	}

	public function getComentarioReceta($receta)
	{
		$qp = $this->createQueryBuilder('r')->select('r')->where('r.Receta = :Receta')->setParameter('Receta', $receta)->addOrderBy('r.fechaCreacion', 'ASC');
		return $qp->getQuery()->getResult();
	}

	public function getComentarioForo($foro)
	{
		$qp = $this->createQueryBuilder('r')->select('r')->where('r.Temaforo = :Temaforo')->setParameter('Temaforo', $foro)->addOrderBy('r.fechaCreacion', 'ASC');
		return $qp->getQuery()->getResult();
	}



}
