<?php

namespace App\AdminBundle\Repository;

/**
 * ComentarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentarioRepository extends \Doctrine\ORM\EntityRepository
{
	public function getNumeroComentario()
	{
		$qp = $this->createQueryBuilder('c')->select('count(c.id)');
		
		return $qp->getQuery()->getSingleScalarResult();
	}



}
