<?php

namespace App\AdminBundle\Repository;

/**
 * HoraIngestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HoraIngestaRepository extends \Doctrine\ORM\EntityRepository
{
}
