<?php

namespace App\AdminBundle\Repository;

/**
 * IngredienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredienteRepository extends \Doctrine\ORM\EntityRepository
{
	public function getNumeroIngrediente()
	{
		$qp = $this->createQueryBuilder('i')->select('count(i.id)');
		
		return $qp->getQuery()->getSingleScalarResult();
	}

}
