<?php

namespace App\AdminBundle\Repository;

/**
 * IngredienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredienteRepository extends \Doctrine\ORM\EntityRepository
{
	public function getNumeroIngrediente()
	{
		$qp = $this->createQueryBuilder('i')->select('count(i.id)');
		
		return $qp->getQuery()->getSingleScalarResult();
	}

	public function listIngredienteTable()
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('i.id','i.nombre', 'i.descripcion', 'i.tipoIngrediente', 'i.unidadMedida', 'i.caloriasUnidad', 'i.celiaco')
            ->from('AdminBundle:Ingrediente', 'i')
            ->getQuery()
            ->getResult();
    }

}
