<?php

namespace App\AdminBundle\Repository;

/**
 * menus_listasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class menus_listasRepository extends \Doctrine\ORM\EntityRepository
{
	public function check($menu, $lista)
	{
		$qp = $this->createQueryBuilder('l')->select('l')->where('l.Lista = :lista')->setParameter('lista', $lista->getId())->andWhere('l.Menu = :menu')->setParameter('menu', $menu->getId());
		return $qp->getQuery()->getOneOrnullResult();
	}
}
