<?php

namespace App\AdminBundle\Repository;

/**
 * SubMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubMenuRepository extends \Doctrine\ORM\EntityRepository
{

	public function check($subMenu)
	{
		$qp = $this->createQueryBuilder('s')->select('s')->where('s.receta = :receta')->setParameter('receta', $subMenu->getReceta())->andWhere('s.Menu = :menu')->setParameter('menu', $subMenu->getMenu())->andWhere('s.HoraIngesta = :HoraIngesta')->setParameter('HoraIngesta', $subMenu->getHoraIngesta());
		return $qp->getQuery()->getOneOrnullResult();
	}
}
