<?php

namespace App\AdminBundle\Repository;

/**
 * TemaForoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemaForoRepository extends \Doctrine\ORM\EntityRepository
{
}
