<?php

namespace App\AdminBundle\Repository;

/**
 * TipoRecetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoRecetaRepository extends \Doctrine\ORM\EntityRepository
{
}
