<?php

namespace Proxies\__CG__\App\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ingrediente extends \App\AdminBundle\Entity\Ingrediente implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\AdminBundle\\Entity\\Ingrediente' . "\0" . 'id', '' . "\0" . 'App\\AdminBundle\\Entity\\Ingrediente' . "\0" . 'nombre', '' . "\0" . 'App\\AdminBundle\\Entity\\Ingrediente' . "\0" . 'descripcion', '' . "\0" . 'App\\AdminBundle\\Entity\\Ingrediente' . "\0" . 'tipoIngrediente', '' . "\0" . 'App\\AdminBundle\\Entity\\Ingrediente' . "\0" . 'unidadMedida', '' . "\0" . 'App\\AdminBundle\\Entity\\Ingrediente' . "\0" . 'caloriasUnidad', '' . "\0" . 'App\\AdminBundle\\Entity\\Ingrediente' . "\0" . 'celiaco', '' . "\0" . 'App\\AdminBundle\\Entity\\Ingrediente' . "\0" . 'ordenescompras', '' . "\0" . 'App\\AdminBundle\\Entity\\Ingrediente' . "\0" . 'cantidadesUtilizadas'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\AdminBundle\\Entity\\Ingrediente' . "\0" . 'id', '' . "\0" . 'App\\AdminBundle\\Entity\\Ingrediente' . "\0" . 'nombre', '' . "\0" . 'App\\AdminBundle\\Entity\\Ingrediente' . "\0" . 'descripcion', '' . "\0" . 'App\\AdminBundle\\Entity\\Ingrediente' . "\0" . 'tipoIngrediente', '' . "\0" . 'App\\AdminBundle\\Entity\\Ingrediente' . "\0" . 'unidadMedida', '' . "\0" . 'App\\AdminBundle\\Entity\\Ingrediente' . "\0" . 'caloriasUnidad', '' . "\0" . 'App\\AdminBundle\\Entity\\Ingrediente' . "\0" . 'celiaco', '' . "\0" . 'App\\AdminBundle\\Entity\\Ingrediente' . "\0" . 'ordenescompras', '' . "\0" . 'App\\AdminBundle\\Entity\\Ingrediente' . "\0" . 'cantidadesUtilizadas'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ingrediente $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeso($peso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeso', [$peso]);

        return parent::setPeso($peso);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeso', []);

        return parent::getPeso();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrdenescompra(\App\AdminBundle\Entity\OrdenCompra $ordenescompra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrdenescompra', [$ordenescompra]);

        return parent::addOrdenescompra($ordenescompra);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrdenescompra(\App\AdminBundle\Entity\OrdenCompra $ordenescompra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrdenescompra', [$ordenescompra]);

        return parent::removeOrdenescompra($ordenescompra);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdenescompras()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdenescompras', []);

        return parent::getOrdenescompras();
    }

    /**
     * {@inheritDoc}
     */
    public function addCantidadesUtilizada(\App\AdminBundle\Entity\CantidadUtilizada $cantidadesUtilizada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCantidadesUtilizada', [$cantidadesUtilizada]);

        return parent::addCantidadesUtilizada($cantidadesUtilizada);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCantidadesUtilizada(\App\AdminBundle\Entity\CantidadUtilizada $cantidadesUtilizada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCantidadesUtilizada', [$cantidadesUtilizada]);

        return parent::removeCantidadesUtilizada($cantidadesUtilizada);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidadesUtilizadas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidadesUtilizadas', []);

        return parent::getCantidadesUtilizadas();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnidadMedida($unidadMedida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnidadMedida', [$unidadMedida]);

        return parent::setUnidadMedida($unidadMedida);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnidadMedida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnidadMedida', []);

        return parent::getUnidadMedida();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaloriasUnidad($caloriasUnidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaloriasUnidad', [$caloriasUnidad]);

        return parent::setCaloriasUnidad($caloriasUnidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaloriasUnidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaloriasUnidad', []);

        return parent::getCaloriasUnidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setCeliaco($celiaco)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCeliaco', [$celiaco]);

        return parent::setCeliaco($celiaco);
    }

    /**
     * {@inheritDoc}
     */
    public function getCeliaco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCeliaco', []);

        return parent::getCeliaco();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoIngrediente($tipoIngrediente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoIngrediente', [$tipoIngrediente]);

        return parent::setTipoIngrediente($tipoIngrediente);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoIngrediente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoIngrediente', []);

        return parent::getTipoIngrediente();
    }

}
