<?php

namespace Proxies\__CG__\App\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Comentario extends \App\AdminBundle\Entity\Comentario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\AdminBundle\\Entity\\Comentario' . "\0" . 'id', '' . "\0" . 'App\\AdminBundle\\Entity\\Comentario' . "\0" . 'contenido', '' . "\0" . 'App\\AdminBundle\\Entity\\Comentario' . "\0" . 'fechaCreacion', '' . "\0" . 'App\\AdminBundle\\Entity\\Comentario' . "\0" . 'Usuarioo', '' . "\0" . 'App\\AdminBundle\\Entity\\Comentario' . "\0" . 'Temaforo', '' . "\0" . 'App\\AdminBundle\\Entity\\Comentario' . "\0" . 'Receta', '' . "\0" . 'App\\AdminBundle\\Entity\\Comentario' . "\0" . 'Tecnica', '' . "\0" . 'App\\AdminBundle\\Entity\\Comentario' . "\0" . 'Menu', '' . "\0" . 'App\\AdminBundle\\Entity\\Comentario' . "\0" . 'Utensilio'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\AdminBundle\\Entity\\Comentario' . "\0" . 'id', '' . "\0" . 'App\\AdminBundle\\Entity\\Comentario' . "\0" . 'contenido', '' . "\0" . 'App\\AdminBundle\\Entity\\Comentario' . "\0" . 'fechaCreacion', '' . "\0" . 'App\\AdminBundle\\Entity\\Comentario' . "\0" . 'Usuarioo', '' . "\0" . 'App\\AdminBundle\\Entity\\Comentario' . "\0" . 'Temaforo', '' . "\0" . 'App\\AdminBundle\\Entity\\Comentario' . "\0" . 'Receta', '' . "\0" . 'App\\AdminBundle\\Entity\\Comentario' . "\0" . 'Tecnica', '' . "\0" . 'App\\AdminBundle\\Entity\\Comentario' . "\0" . 'Menu', '' . "\0" . 'App\\AdminBundle\\Entity\\Comentario' . "\0" . 'Utensilio'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Comentario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenido($contenido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenido', [$contenido]);

        return parent::setContenido($contenido);
    }

    /**
     * {@inheritDoc}
     */
    public function getContenido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenido', []);

        return parent::getContenido();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreacion($fechaCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreacion', [$fechaCreacion]);

        return parent::setFechaCreacion($fechaCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreacion', []);

        return parent::getFechaCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioo(\App\AdminBundle\Entity\Usuario $usuarioo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioo', [$usuarioo]);

        return parent::setUsuarioo($usuarioo);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioo', []);

        return parent::getUsuarioo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTemaforo(\App\AdminBundle\Entity\TemaForo $temaforo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTemaforo', [$temaforo]);

        return parent::setTemaforo($temaforo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTemaforo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTemaforo', []);

        return parent::getTemaforo();
    }

    /**
     * {@inheritDoc}
     */
    public function setReceta(\App\AdminBundle\Entity\Receta $receta = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReceta', [$receta]);

        return parent::setReceta($receta);
    }

    /**
     * {@inheritDoc}
     */
    public function getReceta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReceta', []);

        return parent::getReceta();
    }

    /**
     * {@inheritDoc}
     */
    public function setTecnica(\App\AdminBundle\Entity\Tecnica $tecnica = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTecnica', [$tecnica]);

        return parent::setTecnica($tecnica);
    }

    /**
     * {@inheritDoc}
     */
    public function getTecnica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTecnica', []);

        return parent::getTecnica();
    }

    /**
     * {@inheritDoc}
     */
    public function setMenu(\App\AdminBundle\Entity\Menu $menu = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMenu', [$menu]);

        return parent::setMenu($menu);
    }

    /**
     * {@inheritDoc}
     */
    public function getMenu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenu', []);

        return parent::getMenu();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtensilio(\App\AdminBundle\Entity\Utensilio $utensilio = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtensilio', [$utensilio]);

        return parent::setUtensilio($utensilio);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtensilio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtensilio', []);

        return parent::getUtensilio();
    }

}
