<?php

namespace Proxies\__CG__\App\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Estado extends \App\AdminBundle\Entity\Estado implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\AdminBundle\\Entity\\Estado' . "\0" . 'id', '' . "\0" . 'App\\AdminBundle\\Entity\\Estado' . "\0" . 'fecha', '' . "\0" . 'App\\AdminBundle\\Entity\\Estado' . "\0" . 'peso', '' . "\0" . 'App\\AdminBundle\\Entity\\Estado' . "\0" . 'horasEjercicio', '' . "\0" . 'App\\AdminBundle\\Entity\\Estado' . "\0" . 'caloriasConsumidas', '' . "\0" . 'App\\AdminBundle\\Entity\\Estado' . "\0" . 'Usuario'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\AdminBundle\\Entity\\Estado' . "\0" . 'id', '' . "\0" . 'App\\AdminBundle\\Entity\\Estado' . "\0" . 'fecha', '' . "\0" . 'App\\AdminBundle\\Entity\\Estado' . "\0" . 'peso', '' . "\0" . 'App\\AdminBundle\\Entity\\Estado' . "\0" . 'horasEjercicio', '' . "\0" . 'App\\AdminBundle\\Entity\\Estado' . "\0" . 'caloriasConsumidas', '' . "\0" . 'App\\AdminBundle\\Entity\\Estado' . "\0" . 'Usuario'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Estado $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeso($peso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeso', [$peso]);

        return parent::setPeso($peso);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeso', []);

        return parent::getPeso();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorasEjercicio($horasEjercicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorasEjercicio', [$horasEjercicio]);

        return parent::setHorasEjercicio($horasEjercicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorasEjercicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorasEjercicio', []);

        return parent::getHorasEjercicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaloriasConsumidas($caloriasConsumidas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaloriasConsumidas', [$caloriasConsumidas]);

        return parent::setCaloriasConsumidas($caloriasConsumidas);
    }

    /**
     * {@inheritDoc}
     */
    public function getCaloriasConsumidas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaloriasConsumidas', []);

        return parent::getCaloriasConsumidas();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(\App\AdminBundle\Entity\Usuario $usuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

}
